# This file is part of MinHas_LSH_02817.
# https://github.com/josl/MinHash_02817

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2016, Jose L. Bellod Cisneros & Kosai Al-Nakeeb <bellod.cisneros@gmail.com & kosai@cbs.dtu.dk>

language: python

python:
    - "2.7"
    - "3.4"
    - "pypy"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test
